### STAGE 1: Build ###
FROM node:12.16.0 as build
RUN mkdir /usr/app
WORKDIR /usr/app

# production environment
FROM nginx:1.13.9-alpine
COPY --from=build /usr/app /usr/share/nginx/html
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]